"use client";

import type { ImageLoaderProps } from "next/image";
import { basePath } from "./site-path";

// These widths match the files generated by scripts/build-pages.mjs.
const widths = [320, 640, 960, 1280, 1536];

export default function staticImageLoader({ src, width }: ImageLoaderProps) {
  if (!src.startsWith(`${basePath}/images/`) || !src.endsWith(".webp")) {
    return src;
  }
  const name = src
    .split("/")
    .pop()!
    .replace(/\.webp$/, "");
  const size = widths.find((candidate) => candidate >= width) || widths.at(-1);
  return `${basePath}/images/responsive/${name}-${size}.webp`;
}
